### ISSUE TITLE
Combine spreading vectors with inverted structure and opq

### ISSUE THREAD

**Issue by jasica528** [facebookresearch/spreadingvectors#1]
When i compared sp (spreading vectors) +opq with pca+opq，sp+opq got a higher recall than pca+opq. But when I added an inverted structrue before opq, the 2 methods got similar recall. Can you explain the reason for the results? I did the experiments with 1024-d dl features, and transformed into 128-d features with sp or pca.

**Comment by alexandresablayrolles** [comment]
Could you provide more details about this ? Which dataset do you use ? I assume you use some kind of IVF (k-means or Inverted Multi Index) ? Do you perform OPQ/Catalyst on the residual or on the raw vector ?

**Comment by jasica528** [comment]
> Could you provide more details about this ? Which dataset do you use ? I assume you use some kind of IVF (k-means or Inverted Multi Index) ? Do you perform OPQ/Catalyst on the residual or on the raw vector ?

The original features are 1024 dimensional deep learning features.  I transformed the 1024 dimensional deep learning features into 128 dimensional features with Catalyzer. And use IVF (k-means) with 128 dimensional features. Finally, i perform OPQ on the 128 dimensional residual vectors.

**Comment by alexandresablayrolles** [comment]
Thank you for the details. So in the paper we did not experiment with IVF + quantizer, and the Catalyzer was developed mainly for the lattice quantizer, although it provides improvements when used with other quantizers. My main guess would be that the "uniform" distribution target of the Catalyzer is not a good match for IVF + OPQ (a mixture model seems to be a better fit for IVF). 
Did you cross-validate the parameters (dimension + lambda) taking into account the final performance (after IVF) ?

**Comment by willard-yuan** [comment]
@alexandresablayrolles I'm also interested in the result. If we set lambda=0, i.e. the entropy regularizer takes no effect. Will the result of Catalyzer (1024d -> 128d) + IVF +OPQ outperform PCA (1024d -> 128d) + IVF + OPQ?

**Comment by alexandresablayrolles** [comment]
I don't know what will happen, but you have some numbers it'll be interesting.
