### ISSUE TITLE
How to train 128/256/512 bit catalyzer？

### ISSUE THREAD

**Issue by FredHuang16** [facebookresearch/spreadingvectors#2]

**Comment by alexandresablayrolles** [comment]
With a lattice quantizer, you have to choose the dimension and the squared radius to match the number of bits that you target (see "Zn quantizer" section of the README). 

The dimension is the "--dout" parameter that you specify at training time, and the squared radius R2 is what you will put in the evaluation script as "--quantizer zn_R2" (where you replace R2 by the value you choose).
