### ISSUE TITLE
Different distance measures 

### ISSUE THREAD

**Issue by concrete13377** [facebookresearch/spreadingvectors#4]
In https://github.com/facebookresearch/spreadingvectors/blob/main/train.py#L31 cosine distance is used, but later in https://github.com/facebookresearch/spreadingvectors/blob/7aae7398e9683fc26d7fb2bbeb15eb44bfee8021/train.py#L122 nn.PairwiseDistance(2) is used, why don't you use cosine distance there as well?

**Comment by alexandresablayrolles** [comment]
Cosine and L2 are equivalent because vectors are L2-normalized. However, in one case we do many-to-many matching (i.e. compute the distance of every u[i] to every v[j]), in the other case with pdist we match vectors one by one (u[i] is compared to v[i]).
